import asyncio, json
from playwright.async_api import async_playwright
URL='file:///home/claude/work/saju/site/index.html'
async def fill_me(pg, y, m, d, h=None, mi=0, lunar=False, nick=None):
    await pg.click('#start'); await pg.click('#ask-yes'); await pg.click('.lv[data-lv="mid"]')
    if nick: await pg.fill('#nick', nick); await pg.click('[data-step="1"] button.next:not(.ghost)')
    else: await pg.click('[data-step="1"] button.ghost')
    if lunar: await pg.click('.seg button[data-cal="lunar"]')
    for s,v in [('#me-y',y),('#me-m',m),('#me-d',d)]: await pg.select_option(s,str(v))
    await pg.click('.seg.sex button:has-text("여성")'); await pg.click('#next2'); await pg.wait_for_timeout(150)
    if h is None: await pg.check('#me-hunk')
    else: await pg.select_option('#me-h',str(h)); await pg.select_option('#me-mi',str(mi))
    await pg.click('#go'); await pg.wait_for_timeout(9500)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,accept_downloads=True,permissions=['clipboard-read','clipboard-write'])
        pg=await ctx.new_page(); errs=[]; pg.on('pageerror',lambda e: errs.append(str(e)))
        out={}
        await pg.goto(URL); await pg.click('#door'); await pg.wait_for_timeout(1400)
        await pg.screenshot(path='f_step0.png')
        await pg.click('#start'); await pg.click('#ask-yes'); await pg.click('.lv[data-lv="mid"]'); await pg.wait_for_timeout(200); await pg.screenshot(path='f_step1.png')
        await pg.fill('#nick','쉬고싶은청년'); await pg.click('[data-step="1"] button.next:not(.ghost)'); await pg.wait_for_timeout(200)
        out['b2']=await pg.get_attribute('#bubble-text','data-full')
        await pg.select_option('#me-m','2'); await pg.select_option('#me-d','30'); await pg.click('.seg.sex button:has-text("여성")'); await pg.click('#next2'); await pg.wait_for_timeout(150)
        out['err2']=await pg.inner_text('#err2')
        for s,v in [('#me-y','1990'),('#me-m','5'),('#me-d','15')]: await pg.select_option(s,v)
        await pg.screenshot(path='f_step2.png')
        await pg.click('.seg.sex button:has-text("여성")'); await pg.click('#next2'); await pg.wait_for_timeout(200)
        await pg.select_option('#me-h','14'); await pg.select_option('#me-mi','30'); await pg.screenshot(path='f_step3.png')
        await pg.click('#go'); await pg.wait_for_timeout(300); out['loading']=await pg.get_attribute('#bubble-text','data-full'); await pg.wait_for_timeout(2000); out['loading2']=await pg.get_attribute('#bubble-text','data-full'); await pg.wait_for_timeout(5000); out['loading3']=await pg.get_attribute('#bubble-text','data-full'); await pg.wait_for_timeout(2500)
        out['chart']=(await pg.inner_text('#chart')).replace('\n',' '); out['say']=await pg.inner_text('#say-type')
        await pg.screenshot(path='f_result.png', full_page=True)
        await pg.evaluate('window.__saju.showChap(2)')
        async with pg.expect_download() as dl: await pg.click('#share')
        await (await dl.value).save_as('c_me.png')
        await pg.evaluate('window.__saju.showChap(6)')
        out['sealed_visible']=await pg.is_visible('#y-title')
        await pg.click('#seal-2027 .cover'); await pg.wait_for_timeout(600)
        out['open_visible']=await pg.is_visible('#y-title')
        async with pg.expect_download() as dl: await pg.click('#share-2027')
        await (await dl.value).save_as('c_2027.png')
        await pg.evaluate('window.__saju.showChap(9)')
        await pg.click('#make-link'); await pg.wait_for_timeout(300)
        clip=await pg.evaluate('navigator.clipboard.readText()'); out['clip']=clip
        pg2=await ctx.new_page(); pg2.on('pageerror',lambda e: errs.append(str(e)))
        await pg2.goto(clip.split(' ')[-1]); await pg2.wait_for_timeout(1200)
        out['inv']=await pg2.get_attribute('#bubble-text','data-full'); await pg2.screenshot(path='f_invite.png')
        await fill_me(pg2,1992,3,3)
        out['gh']=await pg2.inner_text('#gh-result')
        async with pg2.expect_download() as dl: await pg2.click('#share-gh')
        await (await dl.value).save_as('c_gh.png')
        # 음력·윤달 오류
        pg3=await ctx.new_page(); await pg3.goto(URL); await pg3.click('#door'); await pg3.wait_for_timeout(1400)
        await pg3.click('#start'); await pg3.click('#ask-yes'); await pg3.click('.lv[data-lv="mid"]'); await pg3.click('[data-step="1"] button.ghost'); await pg3.click('.seg button[data-cal="lunar"]')
        out['leap_visible']=await pg3.is_visible('#me-leap')
        await pg3.check('#me-leap'); await pg3.select_option('#me-y','1990'); await pg3.select_option('#me-m','1'); await pg3.select_option('#me-d','1'); await pg3.click('.seg.sex button:has-text("여성")'); await pg3.click('#next2'); await pg3.wait_for_timeout(150)
        out['leap_err']=await pg3.inner_text('#err2')
        await pg3.uncheck('#me-leap'); await pg3.click('.seg.sex button:has-text("여성")'); await pg3.click('#next2'); await pg3.check('#me-hunk'); await pg3.click('#go'); await pg3.wait_for_timeout(9500)
        out['lunar_note']=await pg3.inner_text('#chart-note'); out['say_noname']=await pg3.inner_text('#say-type')
        await pg3.click('#again'); out['again']=await pg3.get_attribute('#bubble-text','data-full')
        out['scrollW']=[await x.evaluate('document.documentElement.scrollWidth') for x in (pg,pg2,pg3)]
        out['errs']=errs
        print(json.dumps(out,ensure_ascii=False,indent=1)); await b.close()
asyncio.run(main())
